version: '2'

services:
  app:
    image: ignatov/mysql:5.6
    ports:
      - "33056:3306"
    env_file: .env
    networks:
      app_net:
        ipv6_address: 2001:3984:3989::10

networks:
  app_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:      
      - subnet: 2001:3984:3989::/64
        gateway: 2001:3984:3989::1


